### ISSUE TITLE
Live USB image not working

### ISSUE THREAD

**Issue by themarsbar** [vanhoefm/fragattacks#1] opened 2021-05-12 01:12 UTC
Hi,

I've tried using the Live USB image but I cannot get it to work:

```
ubuntu@ubuntu:~$ ifconfig -a
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1409  bytes 142997 (142.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1409  bytes 142997 (142.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlxc025e9278907: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether c0:25:e9:27:89:07  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ubuntu@ubuntu:~$ cd ~/fragattacks/research
ubuntu@ubuntu:~/fragattacks/research$ sudo su
root@ubuntu:/home/ubuntu/fragattacks/research# nmcli radio wifi off
root@ubuntu:/home/ubuntu/fragattacks/research# source venv/bin/activate
(venv) root@ubuntu:/home/ubuntu/fragattacks/research# ./fragattack.py wlxc025e9278907 ping
[05:10:13] This is FragAttack version 1.3.
[05:10:13] WARNING: Unable to check whether you are using patched drivers.
command failed: Invalid argument (-22)
Traceback (most recent call last):
  File "/home/ubuntu/fragattacks/research/fraginternals.py", line 761, in configure_interfaces
    scapy.arch.get_if_index(self.nic_mon)
  File "/etc/skel/fragattacks/research/venv/lib/python3.8/site-packages/scapy/arch/linux.py", line 380, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/etc/skel/fragattacks/research/venv/lib/python3.8/site-packages/scapy/arch/common.py", line 59, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./fragattack.py", line 263, in <module>
    daemon.run()
  File "/home/ubuntu/fragattacks/research/fraginternals.py", line 880, in run
    self.configure_interfaces()
  File "/home/ubuntu/fragattacks/research/fraginternals.py", line 764, in configure_interfaces
    subprocess.check_output(["iw", self.nic_iface, "interface", "add", self.nic_mon, "type", "monitor"])
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['iw', 'wlxc025e9278907', 'interface', 'add', 'monwlxc025e9278', 'type', 'monitor']' returned non-zero exit status 234.
[05:10:13] Closing daemon and cleaning up ...
```

My USB Network adapter is a TP-Link TL-WN722N 

I've also tried with an Alfa AWUS036ACH but I cannot even see this device in ifconfig.

What am I missing?

**Comment by vanhoefm** [comment] 2021-05-12 01:41
That should normally work. Can you use the TL-WN722N to connect to the internet normally (inside the live Ubuntu)?

You can try executing `airmong-ng check kill` and showing its output. After executing this command also try to run the FragAttacks script again. Does executing the command `ls /sys/module` provide output? To further check things can you show the output of:

```
uname -a
ls -d /lib/modules/*/updates
find / -name "beacon_loss_count"
find / -name "fragattack_version"
```

**Comment by themarsbar** [comment] 2021-05-12 02:26
Hi,

I can use this wifi card to connect to my network and get to github.

I ran ```airmong-ng check kill``` and got the same error:
```root@ubuntu:/home/ubuntu/fragattacks/research# airmon-ng check kill

Killing these processes:

    PID Name
   2510 wpa_supplicant
```
````
ubuntu@ubuntu:~/fragattacks/research$ uname -a
Linux ubuntu 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


root@ubuntu:/home/ubuntu/Desktop# ls -d  /lib/modules/*/updates
/lib/modules/5.8.0-43-generic/updates
root@ubuntu:/home/ubuntu/Desktop# ls -l /lib/modules/*/updates/drivers/net/wireless/realtek/rtl8xxxu
total 190
-rw-r--r-- 1 root root 193976 May  9 00:06 rtl8xxxu.ko


ubuntu@ubuntu:~/fragattacks/research$ sudo find / -name "beacon_loss_count"
find: ‘/run/user/999/doc’: Permission denied
find: ‘/run/user/999/gvfs’: Permission denied
find: File system loop detected; ‘/sys/kernel/debug/energy_model’ is part of the same file system loop as ‘/sys/kernel/debug’.

ubuntu@ubuntu:~/fragattacks/research$ sudo find / -name "fragattack_version"
find: ‘/run/user/999/doc’: Permission denied
find: ‘/run/user/999/gvfs’: Permission denied
find: File system loop detected; ‘/sys/kernel/debug/energy_model’ is part of the same file system loop as ‘/sys/kernel/debug’.
```

I saw the code comment around interface name length greater than 15 so renamed it to wlan0 but still the same.

Steve

**Comment by themarsbar** [comment] 2021-05-12 02:45
I've also tried it on another device (MS Surface Pro 3) and get the same experience

**Comment by themarsbar** [comment] 2021-05-12 02:59
```lsusb``` shows it as a TL-WN722N V2 :(

but weird that i can't use the Alfa AWUS036ACH either

**Comment by vanhoefm** [comment] 2021-05-12 07:35
It's very strange that it can't find the "beacon_loss_count" and "fragattack_version" files. Perhaps I made the wrong assumptions on how the live Ubuntu system works on certain devices.

Since you have a USB dongle it's probably easier to install Ubuntu in a virtual machine (e.g. using VirtualBox) and use the tool from inside the VM. You can use USB Wi-Fi dongles from inside a VM.

**Comment by vanhoefm** [comment] 2021-05-12 12:59
Closing this since the problem was caused by using unsupported network cards.

**Closed by vanhoefm** 2021-05-12 12:59 UTC
